version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    volumes:
      - "./app:/app"
    env_file:
      - .env
    restart: always
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lizit
      POSTGRES_USER: lizit
      POSTGRES_PASSWORD: l1z1t4dm1n

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"